# Generated by Django 2.2.5 on 2019-10-23 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('query', models.CharField(max_length=1000)),
                ('attributes', models.CharField(max_length=1000)),
                ('time', models.IntegerField()),
                ('chart_type', models.CharField(max_length=11)),
                ('sum_total', models.IntegerField()),
            ],
            options={
                'db_table': 'mm_charts',
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time', models.IntegerField()),
                ('charts', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'permissions': [('test', '1')],
                'db_table': 'mm_dashboards',
            },
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('fromid', models.IntegerField()),
                ('time', models.IntegerField()),
                ('subject', models.CharField(max_length=250)),
                ('message', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'user_mail',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('time', models.IntegerField()),
                ('message', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'user_notifications',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=11)),
                ('created_by', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'mm_tags',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('time', models.IntegerField()),
                ('subject', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'user_tasks',
            },
        ),
        migrations.CreateModel(
            name='Dashboard_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usergroup_id', models.IntegerField()),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BI.Dashboard')),
            ],
            options={
                'db_table': 'mm_dashboards_groups',
            },
        ),
        migrations.CreateModel(
            name='Chart_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usergroup_id', models.IntegerField()),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BI.Chart')),
            ],
            options={
                'db_table': 'mm_chart_groups',
            },
        ),
    ]
