# Generated by Django 2.2.5 on 2019-10-23 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={'permissions': [('accounting_access', '1'), ('advertising_access', '1'), ('bi_access', '1'), ('circulation_access', '1'), ('editorial_access', '1'), ('production_access', '1')]},
        ),
    ]
