# Generated by Django 2.2.5 on 2019-10-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BI', '0003_auto_20191023_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='height',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='width',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
