# Generated by Django 2.2.5 on 2019-10-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BI', '0004_auto_20191030_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='height',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='width',
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='charts',
            field=models.CharField(max_length=5000),
        ),
    ]
