# Generated by Django 2.2.5 on 2019-11-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BI', '0006_dashboard_filters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='sum_total',
        ),
        migrations.AlterField(
            model_name='chart',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
