# Generated by Django 2.2.5 on 2019-11-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BI', '0007_auto_20191121_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='wheres',
            field=models.CharField(default={}, max_length=1000),
            preserve_default=False,
        ),
    ]
