# Generated by Django 2.2.5 on 2019-11-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BI', '0008_chart_wheres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='attributes',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='chart',
            name='query',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='chart',
            name='wheres',
            field=models.CharField(max_length=5000),
        ),
    ]
