# Generated by Django 2.2.5 on 2019-11-27 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BI', '0009_auto_20191126_1626'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mail',
            table='mm_user_mail',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='mm_user_notifications',
        ),
        migrations.AlterModelTable(
            name='task',
            table='mm_user_tasks',
        ),
    ]
