# Generated by Django 2.2.5 on 2019-12-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BI', '0010_auto_20191127_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='drilldowns',
            field=models.CharField(default={}, max_length=5000),
            preserve_default=False,
        ),
    ]
