# Generated by Django 2.2.5 on 2020-01-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BI', '0011_dashboard_drilldowns'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='groups',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chart',
            name='orders',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
    ]
