# Generated by Django 2.2.5 on 2020-01-03 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BI', '0012_auto_20200103_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chart',
            old_name='groups',
            new_name='groups_bys',
        ),
        migrations.RenameField(
            model_name='chart',
            old_name='orders',
            new_name='order_bys',
        ),
    ]
