# Generated by Django 2.2.5 on 2020-01-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BI', '0014_auto_20200103_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='attributes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chart',
            name='groups_bys',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chart',
            name='order_bys',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chart',
            name='query',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chart',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chart',
            name='wheres',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='charts',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='drilldowns',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='filters',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mail',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mail',
            name='subject',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='subject',
            field=models.TextField(),
        ),
    ]
