# Generated by Django 2.2.5 on 2020-01-03 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BI', '0015_auto_20200103_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chart',
            old_name='attributes',
            new_name='attributes1',
        ),
        migrations.RenameField(
            model_name='chart',
            old_name='chart_type',
            new_name='chart_type1',
        ),
        migrations.RenameField(
            model_name='chart',
            old_name='groups_bys',
            new_name='groups_bys1',
        ),
        migrations.RenameField(
            model_name='chart',
            old_name='order_bys',
            new_name='order_bys1',
        ),
        migrations.RenameField(
            model_name='chart',
            old_name='query',
            new_name='query1',
        ),
        migrations.RenameField(
            model_name='chart',
            old_name='time',
            new_name='time1',
        ),
        migrations.RenameField(
            model_name='chart',
            old_name='title',
            new_name='title1',
        ),
        migrations.RenameField(
            model_name='chart',
            old_name='wheres',
            new_name='wheres1',
        ),
        migrations.RenameField(
            model_name='chart_group',
            old_name='chart',
            new_name='chart1',
        ),
        migrations.RenameField(
            model_name='chart_group',
            old_name='usergroup_id',
            new_name='usergroup_id1',
        ),
    ]
