# Generated by Django 2.2.5 on 2020-01-03 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BI', '0016_auto_20200103_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chart',
            old_name='attributes1',
            new_name='attributes',
        ),
        migrations.RenameField(
            model_name='chart',
            old_name='chart_type1',
            new_name='chart_type',
        ),
        migrations.RenameField(
            model_name='chart',
            old_name='groups_bys1',
            new_name='groups_bys',
        ),
        migrations.RenameField(
            model_name='chart',
            old_name='order_bys1',
            new_name='order_bys',
        ),
        migrations.RenameField(
            model_name='chart',
            old_name='query1',
            new_name='query',
        ),
        migrations.RenameField(
            model_name='chart',
            old_name='time1',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='chart',
            old_name='title1',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='chart',
            old_name='wheres1',
            new_name='wheres',
        ),
        migrations.RenameField(
            model_name='chart_group',
            old_name='chart1',
            new_name='chart',
        ),
        migrations.RenameField(
            model_name='chart_group',
            old_name='usergroup_id1',
            new_name='usergroup_id',
        ),
    ]
