# Generated by Django 2.2.5 on 2020-01-03 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BI', '0017_auto_20200103_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chart',
            old_name='groups_bys',
            new_name='group_bys',
        ),
    ]
