# Generated by Django 2.2.5 on 2020-01-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BI', '0018_auto_20200103_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='selects',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
