# Generated by Django 2.2.5 on 2020-01-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BI', '0019_chart_selects'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('query', models.TextField()),
                ('attributes', models.TextField()),
                ('time', models.IntegerField()),
                ('chart_type', models.CharField(max_length=11)),
                ('selects', models.TextField()),
                ('wheres', models.TextField()),
                ('group_bys', models.TextField()),
                ('order_bys', models.TextField()),
                ('drilldowns', models.TextField()),
            ],
            options={
                'db_table': 'mm_user_charts',
            },
        ),
    ]
