# Generated by Django 2.2.5 on 2020-01-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BI', '0020_user_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_chart',
            name='chart_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_chart',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
