# Generated by Django 2.2.5 on 2020-01-29 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BI', '0022_auto_20200129_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_chart',
            old_name='chart_id',
            new_name='chart',
        ),
        migrations.RenameField(
            model_name='user_chart',
            old_name='user_id',
            new_name='user',
        ),
    ]
