# Generated by Django 2.2.5 on 2020-01-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BI', '0023_auto_20200129_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='drilldown',
            field=models.TextField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chart',
            name='limits',
            field=models.TextField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_chart',
            name='limits',
            field=models.TextField(default={}),
            preserve_default=False,
        ),
    ]
