# Generated by Django 2.2.5 on 2020-01-29 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BI', '0024_auto_20200129_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chart',
            old_name='drilldown',
            new_name='drilldowns',
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='drilldowns',
            new_name='drilldown_options',
        ),
    ]
