# Generated by Django 2.2.5 on 2020-02-05 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BI', '0025_auto_20200129_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('time', models.IntegerField()),
                ('charts', models.TextField()),
                ('filters', models.TextField()),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=10)),
                ('drilldown_options', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('accounting_access', 'Can access Accounting section'), ('advertising_access', 'Can access Advertising section'), ('bi_access', 'Can access Business Intelligence section'), ('circulation_access', 'Can access Circulation section'), ('editorial_access', 'Can access Editorial section'), ('production_access', 'Can access Production section')],
                'db_table': 'mm_user_dashboards',
            },
        ),
    ]
