# Generated by Django 2.2.5 on 2020-02-05 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BI', '0026_user_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_dashboard',
            name='dashboard_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BI.Dashboard'),
            preserve_default=False,
        ),
    ]
