# Generated by Django 2.2.5 on 2020-02-05 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BI', '0027_user_dashboard_dashboard_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_dashboard',
            old_name='dashboard_id',
            new_name='dashboard',
        ),
    ]
