# Generated by Django 2.2.5 on 2020-02-08 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BI', '0028_auto_20200205_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth_Subgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('permission_level', models.IntegerField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
            options={
                'db_table': 'mm_subgroups',
            },
        ),
        migrations.CreateModel(
            name='Auth_User_Subgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BI.Auth_Subgroup')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mm_user_subgroups',
            },
        ),
        migrations.CreateModel(
            name='Auth_Subgroup_permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
                ('subgroup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BI.Auth_Subgroup')),
            ],
            options={
                'db_table': 'mm_subgroup_permissions',
            },
        ),
    ]
