# Generated by Django 2.2.5 on 2020-08-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BI', '0029_auth_subgroup_auth_subgroup_permissions_auth_user_subgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.TextField()),
                ('name', models.CharField(max_length=50)),
                ('password', models.TextField()),
                ('host', models.TextField()),
                ('port', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'mm_source',
            },
        ),
        migrations.AddField(
            model_name='chart',
            name='drilldown_options',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user_chart',
            name='drilldown_options',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user_dashboard',
            name='drilldown_options',
            field=models.TextField(default=''),
        ),
    ]
