# Generated by Django 2.2.5 on 2020-08-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BI', '0030_auto_20200812_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='status',
            field=models.CharField(default='1', max_length=15),
        ),
        migrations.AddField(
            model_name='user_chart',
            name='status',
            field=models.CharField(default='1', max_length=15),
        ),
    ]
