# Generated by Django 2.2.5 on 2020-08-13 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BI', '0031_auto_20200812_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='drilldown_options',
        ),
        migrations.RemoveField(
            model_name='user_dashboard',
            name='drilldown_options',
        ),
    ]
