# Generated by Django 2.2.5 on 2020-08-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BI', '0032_auto_20200813_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='drilldown_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user_chart',
            name='drilldown_status',
            field=models.BooleanField(default=True),
        ),
    ]
