# Generated by Django 2.2.5 on 2020-08-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BI', '0033_auto_20200813_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='user',
            field=models.CharField(default='', max_length=50),
        ),
    ]
