# Generated by Django 2.2.5 on 2020-08-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BI', '0034_source_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='source_id',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='user_chart',
            name='source_id',
            field=models.CharField(default='', max_length=5),
        ),
    ]
