# Generated by Django 2.2.5 on 2020-08-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BI', '0035_auto_20200815_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='source',
            name='user',
            field=models.TextField(),
        ),
    ]
