# Generated by Django 2.2.5 on 2020-08-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BI', '0037_auto_20200818_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='order_id',
            field=models.IntegerField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='user_dashboard',
            name='order_id',
            field=models.IntegerField(default='0', max_length=10),
        ),
    ]
