# Generated by Django 2.2.5 on 2020-08-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BI', '0040_auto_20200818_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='table_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user_chart',
            name='table_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='order_id',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='user_dashboard',
            name='order_id',
            field=models.IntegerField(default='0'),
        ),
    ]
