# Generated by Django 2.2.5 on 2020-08-18 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BI', '0041_auto_20200818_1513'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Source_Group',
        ),
    ]
