# Generated by Django 2.2.5 on 2020-08-18 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('BI', '0042_delete_source_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BI.Source')),
            ],
            options={
                'db_table': 'mm_source_group',
            },
        ),
    ]
