# Generated by Django 2.2.5 on 2020-08-18 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BI', '0043_source_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source_group',
            old_name='group_id',
            new_name='group',
        ),
    ]
