# Generated by Django 2.2.5 on 2020-09-10 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('BI', '0044_auto_20200818_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
            preserve_default=False,
        ),
    ]
