# Generated by Django 2.2.5 on 2020-09-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BI', '0045_dashboard_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='time',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='time',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user_chart',
            name='time',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user_dashboard',
            name='time',
            field=models.TextField(),
        ),
    ]
