# Generated by Django 2.2.5 on 2020-09-17 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BI', '0050_auto_20200917_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='model_name',
            new_name='name',
        ),
    ]
