# Generated by Django 2.2.5 on 2020-11-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BI', '0052_auto_20200923_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='aliases',
            field=models.TextField(default='{}'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_chart',
            name='aliases',
            field=models.TextField(default='{}'),
            preserve_default=False,
        ),
    ]
