# Generated by Django 2.2.5 on 2021-06-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BI', '0053_auto_20201130_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='last_modified',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='chart',
            name='aliases',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='user_chart',
            name='aliases',
            field=models.TextField(default='{}'),
        ),
    ]
