# Generated by Django 2.2.5 on 2021-06-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Org_Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_key', models.CharField(default='', max_length=255)),
                ('meta_value', models.TextField()),
            ],
            options={
                'db_table': 'mm_org_info',
            },
        ),
    ]
