# Generated by Django 2.2.5 on 2021-07-01 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0002_org_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(default='', max_length=255)),
                ('ip_address', models.TextField()),
                ('dashboard_name', models.TextField()),
                ('dashboard_charts', models.TextField()),
                ('dashboard_filters', models.TextField()),
                ('chart_title', models.TextField()),
                ('chart_table_name', models.CharField(default='', max_length=50)),
                ('chart_query', models.TextField()),
                ('chart_attributes', models.TextField()),
                ('chart_chart_type', models.CharField(max_length=11)),
                ('chart_drilldowns', models.TextField()),
                ('chart_selects', models.TextField()),
                ('chart_wheres', models.TextField()),
                ('chart_group_bys', models.TextField()),
                ('chart_order_bys', models.TextField()),
                ('chart_limits', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mm_user_logs',
            },
        ),
        migrations.CreateModel(
            name='Error_Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_id', models.CharField(default='', max_length=10)),
                ('chart_id', models.CharField(default='', max_length=10)),
                ('user_dashboard_id', models.CharField(default='', max_length=10)),
                ('user_chart_id', models.CharField(default='', max_length=10)),
                ('error', models.TextField()),
                ('query', models.TextField()),
                ('dashboard_name', models.TextField()),
                ('dashboard_charts', models.TextField()),
                ('dashboard_filters', models.TextField()),
                ('chart_title', models.TextField()),
                ('chart_table_name', models.CharField(default='', max_length=50)),
                ('chart_query', models.TextField()),
                ('chart_attributes', models.TextField()),
                ('chart_chart_type', models.CharField(max_length=11)),
                ('chart_drilldowns', models.TextField()),
                ('chart_selects', models.TextField()),
                ('chart_wheres', models.TextField()),
                ('chart_group_bys', models.TextField()),
                ('chart_order_bys', models.TextField()),
                ('chart_limits', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mm_user_error_logs',
            },
        ),
    ]
